---
title: "case_study_sites"
author: "Katherine Siegel"
date: "May 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Packages
library(tidyverse)
library(sf)
library(wdpar)
```

## Jamanxim
```{r}
### Get Brazil data
braz_raw <- wdpa_fetch("Brazil")

### Subset to Jamanxim NF
jaman <- subset(braz_raw, WDPA_PID == "351814")

### Look at crs
jaman ### file in EPSG 4326

### Transform to equal area projection (ESRI South America Equidistant Conic)
jaman <- st_transform(jaman, crs = 102033)

### Make 10km and 20km buffers
buff_10 <- st_buffer(jaman, 10000)
buff_20 <- st_buffer(jaman, 20000)

### Drop overlap between buff_20 and buff_10 (want buff_20 as ring)
buff_20_diff <- st_difference(buff_20, st_union(buff_10))

### Drop overlap between buff_10 and jaman (want buff_10 as ring)
buff_10_diff <- st_difference(buff_10, st_union(jaman))

### Add column to each file with what it is
jaman$category <- as.integer(1)
buff_10_diff$category <- as.integer(10)
buff_20_diff$category <- as.integer(20)

### Combine into single file
jaman_buffers <- rbind(jaman, buff_10_diff, buff_20_diff)

### Write feature
st_write(jaman_buffers, 
         "~/Documents/SESYNC/dinamica/processed_layers/jaman_proj_buffers.shp")
```
Convert to raster in gdal
gdal_rasterize -a category -tr 30 30 jaman_proj_buffers.shp jaman_proj_buffers.tiff

ogr2ogr -clipsrc -skipfailures braz_northern_states.shp braz_northern_rds.shp braz_roads_projected.shp
