---
title: "dinamica_prep"
author: "Katherine Siegel"
date: "April 10, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Packages
library(tidyverse)
library(raster)
library(sf)
library(stars)
```

### Amboro-Carrasco

#### Population density
```{r}
### Open shp of buffer
ambcar <- st_read("~/Documents/SESYNC/dinamica/case_study_shp/AmbCar/AmbCarBuf.shp")

### Transform to equal area projection (ESRI South America Equidistant Conic)
ambcar_pr <- st_transform(ambcar, crs = 102033)

### Open shp of municipios
municip <- st_read("~/Documents/SESYNC/dinamica/bolivia_dinamica_data/pop_dens/municipios_339_pob2012.shp") %>% 
  st_transform(., crs = 102033)
st_write(municip, 
         "~/Documents/SESYNC/dinamica/bolivia_dinamica_data/pop_dens/municipios_339_pob2012_projected.shp")

### intersect pop density and PA polygon
ambcar_pd <- st_intersection(ambcar_pr, municip)
st_write(ambcar_pd, 
         "~/Documents/SESYNC/dinamica/processed_layers/bol_popdens.shp")
```
Converted this to raster using gdal in gitbash: 
gdal_rasterize -a densidad12 -tr 30 30 bol_popdens.shp bol_popdens.tiff

Made raster of population density in ArcMap (Polygon to Raster): pd_2012 (cell size = 30)
```{r}
bolpd <- raster("~/Documents/SESYNC/dinamica/bol_pd.tif")
```

### Rivers

#### Rios principales
Convert crs
```{r}
rios_princ <- st_read("~/Documents/SESYNC/dinamica/bolivia_dinamica_data/rios/rios_2002/rios_principales.shp") %>%
  st_transform(., crs = 102033)

### Save projected version
st_write(rios_princ, "~/Documents/SESYNC/dinamica/bolivia_dinamica_data/rios/rios_2002/rios_principales_projected.shp")
```

Used gdal to make raster ()
