---
title: "neighbor_pix"
author: "Katherine Siegel"
date: "January 26, 2021"
output: html_document
---

## Description
Calculate % of neighboring pixels that are a different land cover class. Use subset of Brazil first to figure it out.

## Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Open packages
library(tidyverse)
library(sf)
library(raster)
library(sp)
library(rgdal)
# library(lulcc)
# library(gsubfn)
# library(caret)
library(landscapemetrics)

#### Function to check correlation
cor.prob <- function (X, dfr = nrow(X) - 2) {
  R <- cor(X, use="pairwise.complete.obs")
  above <- row(R) < col(R)
  r2 <- R[above]^2
  Fstat <- r2 * dfr/(1 - r2)
  R[above] <- 1 - pf(Fstat, 1, dfr)
  R[row(R) == col(R)] <- NA
  R
}
flattenSquareMatrix <- function(m) {
  if( (class(m) != "matrix") | (nrow(m) != ncol(m))) stop("Must be a square matrix.") 
  if(!identical(rownames(m), colnames(m))) stop("Row and column names must be equal.")
  ut <- upper.tri(m)
  data.frame(i = rownames(m)[row(m)[ut]],
             j = rownames(m)[col(m)[ut]],
             cor=t(m)[ut],
             p=m[ut])
}
```

### Owen's method
```{r}
### Open data
bra_samp <- raster("bra_sample.tif")

### Function to calculate % neighbors of different types
percent_different_neighbors <- function(cell) {
  # pull neighboring values
  # see ?adjacent for the arguments used here
  x <- getValues(bra_samp)[adjacent(bra_samp, 
                                    cells = cell, 
                                    directions = 8, 
                                    pairs = F, 
                                    include = T)]
  # calculate the percent of them that are not equal to the focal cell (i.e., not equal to the first value of x)
  perc_diff <- sum(x!=x[1])/(length(x)-1)*100
  return(perc_diff)
}

### Run on sample matrix: apply function to each cell
perc_diff_values <- map_dbl(1:ncell(bra_samp),
                            ~percent_different_neighbors(.))

# then make a new raster with the cells
perc_diff_raster <- bra_samp %>% setValues(perc_diff_values)
plot(bra_samp)
plot(perc_diff_raster)
```

#### Try moving window method
```{r}
### Open data
bra_samp <- raster("D:/dinamica/brazil_simple/data/bra_sample.tif")

### Set moving window
moving_window <- matrix(1, nrow = 3, ncol = 3)

### Test
test_result <- window_lsm(bra_samp,
                          window = moving_window,
                          what = c("lsm_l_pr"))
### Where the lsm_l_pr value = 1, 100% of surrounding pixels are the same as the focal pixel 

### Try adjacencies
adj <- get_adjacencies(bra_samp, 8, "full")
```

#### Try ArcMap method in R
```{r}
### Open data
bra_samp <- raster("D:/dinamica/brazil_simple/data/bra_sample.tif")

### Make pt at center of each pixel
pts <- rasterToPoints(bra_samp,
                      # fun = function(x){x<8},
                      spatial = TRUE)

### Convert to sf and set crs
pts <- st_as_sf(pts)
st_crs(pts) <- crs(bra_samp)

### Make uid for pts
pts$uid <- 1:nrow(pts)

### Buffer pts
pts_buff <- st_buffer(pts, 42.427)

### Intersect pts
pts_inter <- st_intersection(pts_buff, pts)

### Drop rows where uid = uid.1, 1961398
pts_inter <- pts_inter %>%
  filter(!(uid == uid.1))

### Summarize
pts_summ <- pts_inter
st_geometry(pts_summ) <- NULL
pts_summ <- pts_summ %>%
  dplyr::select(uid, lc_pixel = bra_sample,
                lc_surround = bra_sample.1,
                uid.1)
pts_summ <- pts_summ %>%
  group_by(uid, lc_pixel, lc_surround) %>%
  summarise(n_pixels = n())

### Number of adjacent pixels per pixel
pts_per_pix <- pts_summ %>%
  group_by(uid) %>%
  summarize(n_adj_pix = sum(n_pixels))

### Merge in
pts_summ <- merge(pts_summ, pts_per_pix,
                  by = "uid")

### Calc %
pts_summ <- pts_summ %>%
  mutate(pct_surround = n_pixels/n_adj_pix)


```

