---
title: "peru_dinamica"
author: "Katherine Siegel"
date: "August 26, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### Packages
library(tidyverse)
library(raster)
library(sf)
```

Make rasterbrick for Peru static layers

### Open raster layers
```{r}
### Get names of all files in folder
peru_layers <- list.files(path = "D:/Peru/TIffs/",
                          pattern = "*\\.tif$",
                          full.names = TRUE)
### Open all rasters
aspect <- raster(peru_layers[[1]])
cropsuit <- raster(peru_layers[[2]])
elev <- raster(peru_layers[[3]])
mines <- raster(peru_layers[[4]])
natparks <- raster(peru_layers[[5]])
popden <- raster(peru_layers[[6]])
pov <- raster(peru_layers[[7]])
rain <- raster(peru_layers[[8]])
rivers <- raster(peru_layers[[9]])
roads <- raster(peru_layers[[10]])
slope <- raster(peru_layers[[11]])
urban <- raster(peru_layers[[12]])
```

### Clip base layer to exclude BOL
Use elevation as base layer of rasters
```{r}
### Open new buffer shapefile
tam_bah <- st_read("D:/Peru/Buffer/Buffer.shp")
# plot(tam_bah[1])

### Crop elevation raster to new shp extent
elev_tambah <- raster::crop(elev, as.vector(st_bbox((tam_bah))))
plot(elev_tambah)
```


### Resample all rasters to match elev_tambah
```{r}
### Resample crop suitability
aspect_resample <- raster::resample(aspect, elev_tambah, "bilinear")
cs_resample <- raster::resample(cropsuit, elev_tambah, "bilinear")
mines_resample <- raster::resample(mines, elev_tambah, "bilinear")
natparks_resample <- raster::resample(natparks, 
                                      elev_tambah, "bilinear")
popden_resample <- raster::resample(popden, elev_tambah, "bilinear")
pov_resample <- raster::resample(pov, elev_tambah, "bilinear")
precip_resample <- raster::resample(rain, elev_tambah, "bilinear")
riv_resample <- raster::resample(rivers, elev_tambah, "bilinear")
rd_resample <- raster::resample(roads, elev_tambah, "bilinear")
slope_resample <- raster::resample(slope, elev_tambah, "bilinear")
urban_resample <- raster::resample(urban, elev_tambah, "bilinear")

### Make brick
peru_brick <- raster::brick(aspect_resample,
                            cs_resample, 
                            rd_resample, 
                            riv_resample,
                            urban_resample,
                            mines_resample,
                            popden_resample,
                            pov_resample,
                            natparks_resample,
                            precip_resample,
                            slope_resample,
                            elev_tambah)

### Write out brick
writeRaster(peru_brick, 
            filename = "D:/Peru/peru_static_vars.tif", 
            format = "GTiff",
            overwrite = TRUE, 
            options = c("INTERLEAVE=BAND","COMPRESS=LZW"))
```

